services:
  codemate_web:
    container_name: codemate_web
    image: nginx:alpine
    volumes:
      - ./public:/var/www/public:ro
      - ./storage/app/public:/var/www/storage/app/public:ro
      - ./docker_dev/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker_dev/nginx/site.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    logging: &logging
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    depends_on:
      - codemate_app
    networks:
      - default

  codemate_app:
    container_name: codemate_app
    image: codemate_app
    build:
      dockerfile: docker_dev/app/Dockerfile
      context: .
    volumes:
      - .:/var/www
      - ./docker_dev/app/prepare-app.sh:/docker-entrypoint.d/prepare-app.sh:ro
    tmpfs:
      #- /tmp
      - /var/www/storage/debugbar
      - /var/www/storage/framework/cache/data
      #- /var/www/storage/framework/views
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    logging: *logging
    depends_on:
      - codemate_db
    networks:
      - default

  codemate_db:
    container_name: codemate_db
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
      PGDATA: /var/pg_data
    volumes:
      - db-data:/var/pg_data
      - ./docker_dev/db/pg.conf:/etc/postgresql/pg.conf
      - ./docker_dev/db/create-main-db.sh:/docker-entrypoint-initdb.d/create-main-db.sh
    command: [ "postgres", "-c", "config_file=/etc/postgresql/pg.conf" ]
    restart: unless-stopped
    logging: *logging
    networks:
      - default

networks:
  default:

volumes:
  db-data:
    name: codemate_db_data
